sudo : required
dist: xenial
language:
  - ruby 
  - python
rvm:
  -  2.2.5
python:
  - "3.4"
before_install:
  # - sudo apt-get install python3-pip
  - sudo apt-get install pandoc
  - gem install asciidoctor
  - pip --version
install: 
  # - gem install html-proofer
  - pip install requests
  - pip install  -r req.txt
  # - sudo apt install cloc
script:
  # - ruby proofer.rb
  # - python app.py
  - git checkout master
  - bash deploy.sh
  - bash push.sh

branches:
    only:
      -  master
