group: deprecated-2017Q3
sudo : required
dist: xenial
language:
  - ruby 
  - python
rvm:
  -  2.2.5
before_install:
  - sudo apt-get install pandoc
  - gem install asciidoctor
install: 
  # - gem install html-proofer
  - pip3 install requests
  - pip3 install  -r req.txt
  # - sudo apt install cloc
script:
  # - ruby proofer.rb
  # - python app.py
  - git checkout master
  - bash deploy.sh
  - bash push.sh

branches:
    only:
      -  master
